### ISSUE TITLE
Ошибка при подключении

### ISSUE THREAD

**Issue by aimat163** [pavelmaksimov/tapi-yandex-metrika#3]
При получении отчета, 

```
info = client.create().post(params=params)
request_id = info["log_request"]["request_id"]

report = client.download(requestId=request_id).get()
```

получаю ошибку вида

`During handling of the above exception, another exception occurred:

YandexMetrikaDownloadReportError          Traceback (most recent call last)
<class 'str'>: (<class 'TypeError'>, TypeError('__str__ returned non-string (type NoneType)'))

During handling of the above exception, another exception occurred:`

Скрин: http://joxi.ru/J2bG3xDTM453XA 

Подскажите, что делаю не так?

**Comment by pavelmaksimov** [comment]
Ошибку попозже исправлю, а пока можешь сделать так, это должно помочь:
```request_id = info.data["log_request"]["request_id"]```

**Comment by breeze90** [comment]
Здравствуйте. А что это за ошибка?

Пару дней назад этот же самый запрос работал.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 line 21, in <module>
    result = api.download(requestId=request_id).get()
 line 362, in get
    return self._make_request("GET", *args, **kwargs)
 line 336, in _make_request
    self._api.wrapper_call_exception(
line 83, in wrapper_call_exception
    raise exceptions.YandexMetrikaApiError(response)
tapi_yandex_metrika.exceptions.YandexMetrikaApiErrorINFO:root:HEADERS = {'Cache-Control': 'must-revalidate,no-cache,no-store', 'Content-Length': '514', 'Content-Type': 'text/html;charset=iso-8859-1', 'Pragma': 'no-cache', 'X-Content-Type-Options': 'nosniff', 'X-Frame-Options': 'DENY', 'X-XSS-Protection': '1; mode=block'}
INFO:root:URL = https://api-metrika.yandex.net/management/v1/counter/94851830/logrequest/32638116/part/0/download
: 404 Not Found  <html>
<head>
<meta http-equiv="Content-Type" content="text/html;charset=ISO-8859-1"/>
<title>Error 404 Not Found</title>
</head>
<body><h2>HTTP ERROR 404 Not Found</h2>
<table>
<tr><th>URI:</th><td>/management/v1/counter/94854540/logrequest/32638116/part/0/download</td></tr>
<tr><th>STATUS:</th><td>404</td></tr>
<tr><th>MESSAGE:</th><td>Not Found</td></tr>
<tr><th>SERVLET:</th><td>faced</td></tr>
</table>
<hr/><a href="https://eclipse.org/jetty">Powered by Jetty:// 9.4.45.v20220203</a><hr/>

</body>
</html>

**Comment by pavelmaksimov** [comment]
> Здравствуйте. А что это за ошибка?
> 
> Пару дней назад этот же самый запрос работал.
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last): line 21, in result = api.download(requestId=request_id).get() line 362, in get return self._make_request("GET", *args, **kwargs) line 336, in _make_request self._api.wrapper_call_exception( line 83, in wrapper_call_exception raise exceptions.YandexMetrikaApiError(response) tapi_yandex_metrika.exceptions.YandexMetrikaApiErrorINFO:root:HEADERS = {'Cache-Control': 'must-revalidate,no-cache,no-store', 'Content-Length': '514', 'Content-Type': 'text/html;charset=iso-8859-1', 'Pragma': 'no-cache', 'X-Content-Type-Options': 'nosniff', 'X-Frame-Options': 'DENY', 'X-XSS-Protection': '1; mode=block'} INFO:root:URL = https://api-metrika.yandex.net/management/v1/counter/94851830/logrequest/32638116/part/0/download : 404 Not Found
> 
> <title>Error 404 Not Found</title>
> ## HTTP ERROR 404 Not Found
> URI:	/management/v1/counter/94854540/logrequest/32638116/part/0/download
> STATUS:	404
> MESSAGE:	Not Found
> SERVLET:	faced
> [Powered by Jetty:// 9.4.45.v20220203](https://eclipse.org/jetty)

Пытаетесь скачать несуществующий отчет. Яндекс метрика регулярно удаляет отчеты, их нужно пересоздавать.

**Comment by breeze90** [comment]
Я использую этот код

api = YandexMetrikaLogsapi(access_token=ACCESS_TOKEN,
                           default_url_params={'counterId': COUNTER_ID},
                           wait_report=True,
                           receive_all_data=True
                           )
params = {
    "fields": "ym:s:dateTime,ym:s:clientID,ym:s:isNewUser,ym:s:regionCity,ym:s:visitDuration,ym:s:goalsID,ym:s:UTMCampaign,ym:s:UTMContent,ym:s:lastDirectPhraseOrCond,ym:s:deviceCategory,ym:s:operatingSystemRoot",
    "source": "visits",
    "date1": "2023-11-06",
    "date2": "2023-11-06"
}

result = api.create().post(params=params)
request_id = result().data["log_request"]["request_id"]
result = api.download(requestId=request_id).get()
data = result().data

Как мне его изменить, чтобы создать отчет заново?

Я думал, что каждый этот запрос - это создание нового отчета, которые через десятки секунд будет скачан.

может, метрика что-то изменила?

**Comment by GeorgyErm** [comment]
Присоединяюсь: 404 ошибка, до этого работало

**Comment by GeorgyErm** [comment]
@pavelmaksimov новый api_root https://api-metrica.yandex.net/ через c

**Comment by pavelmaksimov** [comment]
https://github.com/pavelmaksimov/tapi-yandex-metrika/issues/3#issuecomment-1810729934 не вижу в документации такие изменений https://yandex.ru/dev/metrika/doc/api2/logs/queries/getlogrequests.html

**Comment by pavelmaksimov** [comment]
> > Здравствуйте. А что это за ошибка?
> > Пару дней назад этот же самый запрос работал.
> > During handling of the above exception, another exception occurred:
> > Traceback (most recent call last): line 21, in result = api.download(requestId=request_id).get() line 362, in get return self._make_request("GET", *args, **kwargs) line 336, in _make_request self._api.wrapper_call_exception( line 83, in wrapper_call_exception raise exceptions.YandexMetrikaApiError(response) tapi_yandex_metrika.exceptions.YandexMetrikaApiErrorINFO:root:HEADERS = {'Cache-Control': 'must-revalidate,no-cache,no-store', 'Content-Length': '514', 'Content-Type': 'text/html;charset=iso-8859-1', 'Pragma': 'no-cache', 'X-Content-Type-Options': 'nosniff', 'X-Frame-Options': 'DENY', 'X-XSS-Protection': '1; mode=block'} INFO:root:URL = https://api-metrika.yandex.net/management/v1/counter/94851830/logrequest/32638116/part/0/download : 404 Not Found
> > <title>Error 404 Not Found</title>
> > ## HTTP ERROR 404 Not Found
> > URI:	/management/v1/counter/94854540/logrequest/32638116/part/0/download
> > STATUS:	404
> > MESSAGE:	Not Found
> > SERVLET:	faced
> > [Powered by Jetty:// 9.4.45.v20220203](https://eclipse.org/jetty)
> 
> Пытаетесь скачать несуществующий отчет. Яндекс метрика регулярно удаляет отчеты, их нужно пересоздавать.

Я понял. Смотрите на ссылку, на которую идет запрос, она содержит "management". Похоже вы использовали класс YandexMetrikaManagement. Для логсапи надо использовать YandexMetrikaLogsapi
